# Generated by Django 6.0.5 on 2026-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_vehicles', models.IntegerField(default=50)),
                ('name', models.CharField(default='Meu Estacionamento', max_length=100)),
            ],
            options={
                'verbose_name': 'Configuração',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Carro'), ('moto', 'Moto')], default='car', max_length=10),
        ),
    ]
